# [lint]
# # Enable rule for import sorting and docstrings
# extend-select = ["I", "D"]

# # Do not require documentation for every single function/method.
# ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107"]
