[project]
name = "dataflow"
version = "0.1.0"
description = "Responsible for handling data flow for CMU Maps"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "clerk-backend-api>=4.2.0",
  "minio>=7.2.20",
  "pyjwt>=2.10.1",
  "python-dotenv>=1.2.1",
  "requests>=2.32.5",
]
