name: "cmumaps"

services:
  dev:
    container_name: cmumaps-dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: cmumaps-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: donotuseinprod
      POSTGRES_DB: cmumaps
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: cmumaps-redis
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
